---
title: "git_01"
author: "Desiree De La Rosa"
date: "summer 2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Build a Poem with commits to different branches
Our project will be done using a sequence of save and commits and branch actions.
<!-- Do not modify or change any text in "!--" bracketed areas such as this --- these are instructions to
you, if you change any of this the git program will notice it and compromise your git merging strategy !-->

## First Verse 
<!--Put the first five lines of a poem by Lewis Carrol in this section!-->


“Will you walk a little faster?”  

said a whiting to a snail.  

“There’s a porpoise close behind us,  

and he’s treading on my tail.  

See how eagerly the lobsters and  


## Second Verse
<!--Put the first five lines of a poem by Robert Frost here!-->


Some say the world will end in fire,  
Some say in ice.  
From what I’ve tasted of desire  
I hold with those who favor fire.  
But if it had to perish twice,  


## Third Verse
<!--Put the first two verses of The Walrus and the Carpenter here!-->


The sun was shining on the sea,  
Shining with all his might:  
He did his very best to make  
The billows smooth and bright–  


## Last Verse
<!--Put a short poem of your choice 8-20 lines,here!-->


From childhood’s hour I have not been  
As others were—I have not seen   
As others saw—I could not bring   
My passions from a common spring—  
From the same source I have not taken  
My sorrow—I could not awaken   
My heart to joy at the same tone—  
And all I lov’d—I lov’d alone—  

